language: node_js
node_js: 
    - '11'
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "${USERNAME}"
  - git config user.email "${UESREMAIL}"
  - git add -A
  - git commit -m "Update docs"
  - git push --force  "https://${GH_TOKEN}@${GH_REF}" "master:${GH_BRANCH}"
branches:
  only:
    - master
env:
 global:
   #GH_REF: github.com/zhufengnodejs/zfblog2.git 
